source 'https://github.com/CocoaPods/Specs.git'
platform :ios,			'7.0'
inhibit_all_warnings!

target:'MengWechat'

xcodeproj 'MengWechat.xcodeproj'
workspace 'MengWechat.xcworkspace'

pod 'BabyBluetooth', '~> 0.5.0'
pod 'FMDB', '~> 2.6.2'
pod 'Masonry', '~> 1.0.1'

pod 'LCHeheViewController',:git=>"https://github.com/mlcldh/MengPodTest"
#pod 'LCHeheViewController', '~> 0.0.1'

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end

